# Open HepRepXML
/vis/open HepRepXML

# Don't write the geometry to every event; just write it once
/vis/heprep/appendGeometry false
/vis/heprep/addPointAttributes 1

/vis/drawVolume
/vis/viewer/set/lineSegmentsPerCircle 240
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/vis/verbose warnings